services:
  - type: web
    name: rental-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn rental.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: rental.settings
